### ISSUE TITLE
나는 질문이 있다, 당신에게.

### ISSUE THREAD

**Issue by minhyuuk** [GSMYunsung/GSMYunsung#1]
I was impressed to see your GitHub. Come to my company.  If you join our company, I'll give you five won.

**Comment by GSMYunsung** [comment]
Oh, minhuk... As you can see, I switched to app development. I will study kolutin to become an app developer haha

**Comment by minhyuuk** [comment]
> I was impressed to see your GitHub. Come to my company. If you join our company, I'll give you five won.
